/** Canonical audit action names. Keep stable: they are queried and reported on. */
export const AuditAction = {
  ADMIN_LOGIN_SUCCEEDED: 'admin.login.succeeded',
  ADMIN_LOGIN_FAILED: 'admin.login.failed',
  ADMIN_LOGIN_LOCKED: 'admin.login.locked',
  ADMIN_LOGOUT: 'admin.logout',
  ADMIN_REFRESH_REUSE_DETECTED: 'admin.refresh.reuse_detected',
  ADMIN_USER_CREATED: 'admin_user.created',
  ADMIN_USER_UPDATED: 'admin_user.updated',
  HELMET_MODEL_CREATED: 'helmet_model.created',
  HELMET_MODEL_UPDATED: 'helmet_model.updated',
  BATCH_CREATED: 'batch.created',
  BATCH_GENERATION_STARTED: 'batch.generation.started',
  BATCH_GENERATION_COMPLETED: 'batch.generation.completed',
  BATCH_GENERATION_FAILED: 'batch.generation.failed',
  BATCH_MARKED_PRINTED: 'batch.marked_printed',
  BATCH_PIN_ESCROW_PURGED: 'batch.pin_escrow.purged',
  BATCH_EXPORT_MANUFACTURING_CSV: 'batch.export.manufacturing_csv',
  HELMET_STATUS_CHANGED: 'helmet.status.changed',
  CUSTOMER_CREATED: 'customer.created',
  CUSTOMER_LOGIN: 'customer.login',
  CUSTOMER_LOGIN_FAILED: 'customer.login.failed',
  CUSTOMER_LOGIN_LOCKED: 'customer.login.locked',
  CUSTOMER_PASSWORD_CHANGED: 'customer.password.changed',
  CUSTOMER_PASSWORD_RESET: 'customer.password.reset',
  CUSTOMER_RECOVERY_VERIFIED: 'customer.recovery.verified',
  CUSTOMER_RECOVERY_FAILED: 'customer.recovery.failed',
  CUSTOMER_RECOVERY_LOCKED: 'customer.recovery.locked',
  CUSTOMER_RECOVERY_CODE_ROTATED: 'customer.recovery_code.rotated',
  CUSTOMER_LOGOUT: 'customer.logout',
  CUSTOMER_SESSIONS_REVOKED: 'customer.sessions.revoked',
  CUSTOMER_REFRESH_REUSE_DETECTED: 'customer.refresh.reuse_detected',
  CUSTOMER_PROFILE_UPDATED: 'customer.profile.updated',
  HELMET_ACTIVATED: 'helmet.activated',
  ACTIVATION_PIN_CONSUMED: 'helmet.activation_pin.consumed',
  ACTIVATION_FAILED: 'helmet.activation.failed',
  ACTIVATION_LOCKED: 'helmet.activation.locked',
  EMERGENCY_PROFILE_UPDATED: 'emergency_profile.updated',
  EMERGENCY_PROFILE_PHOTO_UPDATED: 'emergency_profile.photo.updated',
  EMERGENCY_PROFILE_ENABLED: 'emergency_profile.enabled',
  EMERGENCY_PROFILE_DISABLED: 'emergency_profile.disabled',
  EMERGENCY_CONTACTS_CHANGED: 'emergency_contacts.changed',
  EMERGENCY_VISIBILITY_CHANGED: 'emergency_visibility.changed',
} as const;
export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction];
