/** Response envelope shared by every API endpoint. */

export interface PaginationMeta {
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
}

export interface ApiSuccess<T> {
  success: true;
  data: T;
  meta?: PaginationMeta;
}

export interface ApiErrorBody {
  code: ErrorCode | string;
  message: string;
  details?: unknown;
  requestId?: string;
}

export interface ApiFailure {
  success: false;
  error: ApiErrorBody;
}

export type ApiResponse<T> = ApiSuccess<T> | ApiFailure;

export interface Paginated<T> {
  items: T[];
  meta: PaginationMeta;
}

export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  HELMET_NOT_FOUND: 'HELMET_NOT_FOUND',
  HELMET_MODEL_NOT_FOUND: 'HELMET_MODEL_NOT_FOUND',
  HELMET_MODEL_ARCHIVED: 'HELMET_MODEL_ARCHIVED',
  BATCH_NOT_FOUND: 'BATCH_NOT_FOUND',
  BATCH_GENERATION_IN_PROGRESS: 'BATCH_GENERATION_IN_PROGRESS',
  BATCH_ALREADY_GENERATED: 'BATCH_ALREADY_GENERATED',
  BATCH_NOT_GENERATED: 'BATCH_NOT_GENERATED',
  BATCH_ALREADY_PRINTED: 'BATCH_ALREADY_PRINTED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  HELMET_ALREADY_ACTIVATED: 'HELMET_ALREADY_ACTIVATED',
  HELMET_NOT_ACTIVATABLE: 'HELMET_NOT_ACTIVATABLE',
  HELMET_HAS_OWNER: 'HELMET_HAS_OWNER',
  INVALID_ACTIVATION_PIN: 'INVALID_ACTIVATION_PIN',
  ACTIVATION_ATTEMPTS_EXCEEDED: 'ACTIVATION_ATTEMPTS_EXCEEDED',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  INVALID_PHONE_NUMBER: 'INVALID_PHONE_NUMBER',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  RESET_TOKEN_INVALID: 'RESET_TOKEN_INVALID',
  PROFILE_INCOMPLETE: 'PROFILE_INCOMPLETE',
  PROFILE_REQUIREMENT: 'PROFILE_REQUIREMENT',
  EMERGENCY_PROFILE_DISABLED: 'EMERGENCY_PROFILE_DISABLED',
  CONTACT_NOT_FOUND: 'CONTACT_NOT_FOUND',
  CONTACT_LIMIT_REACHED: 'CONTACT_LIMIT_REACHED',
  INVALID_FILE: 'INVALID_FILE',
  FORBIDDEN_RESOURCE: 'FORBIDDEN_RESOURCE',
  HELMET_NOT_OWNED: 'HELMET_NOT_OWNED',
  HELMET_NOT_TRANSFERABLE: 'HELMET_NOT_TRANSFERABLE',
  TRANSFER_NOT_FOUND: 'TRANSFER_NOT_FOUND',
  TRANSFER_CODE_INVALID: 'TRANSFER_CODE_INVALID',
  TRANSFER_CODE_EXPIRED: 'TRANSFER_CODE_EXPIRED',
  TRANSFER_ALREADY_USED: 'TRANSFER_ALREADY_USED',
  TRANSFER_ATTEMPTS_EXCEEDED: 'TRANSFER_ATTEMPTS_EXCEEDED',
  CANNOT_TRANSFER_TO_CURRENT_OWNER: 'CANNOT_TRANSFER_TO_CURRENT_OWNER',
  HELMET_ALREADY_LOST: 'HELMET_ALREADY_LOST',
  HELMET_ALREADY_STOLEN: 'HELMET_ALREADY_STOLEN',
  HELMET_NOT_LOST: 'HELMET_NOT_LOST',
  HELMET_NOT_STOLEN: 'HELMET_NOT_STOLEN',
  HELMET_ACTION_NOT_ALLOWED: 'HELMET_ACTION_NOT_ALLOWED',
  HELMET_NOT_DEACTIVATABLE: 'HELMET_NOT_DEACTIVATABLE',
  HELMET_NOT_RECOVERABLE: 'HELMET_NOT_RECOVERABLE',
  HELMET_REPLACED: 'HELMET_REPLACED',
  OWNERSHIP_NOT_FOUND: 'OWNERSHIP_NOT_FOUND',
  OWNERSHIP_ALREADY_REVOKED: 'OWNERSHIP_ALREADY_REVOKED',
  REPLACEMENT_INVALID: 'REPLACEMENT_INVALID',
  RECENT_AUTH_REQUIRED: 'RECENT_AUTH_REQUIRED',
  CONFIRMATION_MISMATCH: 'CONFIRMATION_MISMATCH',
  WARRANTY_NOT_FOUND: 'WARRANTY_NOT_FOUND',
  WARRANTY_ALREADY_REGISTERED: 'WARRANTY_ALREADY_REGISTERED',
  WARRANTY_NOT_AVAILABLE: 'WARRANTY_NOT_AVAILABLE',
  WARRANTY_NOT_REGISTRABLE: 'WARRANTY_NOT_REGISTRABLE',
  INVALID_PURCHASE_DATE: 'INVALID_PURCHASE_DATE',
  WARRANTY_INVALID_STATE: 'WARRANTY_INVALID_STATE',
  WARRANTY_PROOF_NOT_FOUND: 'WARRANTY_PROOF_NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
